services:
  - type: web
    name: dress-inventory
    env: php
    branch: main
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
