services:
  - type: web
    name: dress-shop-inventory
    env: docker
    region: oregon  # or change to your nearest region
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter: []
    autoDeploy: true
